-- 코드를 작성해주세요
SELECT E.YEAR, M.MAX_COLONY-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID 
FROM (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY, ID
     FROM ECOLI_DATA) AS E 
     JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
            FROM ECOLI_DATA
            GROUP BY YEAR(DIFFERENTIATION_DATE)) AS M
            ON E.YEAR = M.YEAR
ORDER BY YEAR, YEAR_DEV 